language: node_js
cache:
  directories:
    - Ëœ/.npm:
    node_js:
    -"14.16.0"
git:
  depth: 3
scripth:
  - yarn build
deploy:
  provider: pages
  edge: true,
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy Release"
  on: 
    branch: master